# These are supported funding model platforms

github: thuongtruong1009
ko_fi: thuongtruong1009
open_collective: ambition-fund
custom: ["https://paypal.me/thuongtruong1009", "https://nhantien.momo.vn/0917085937"]