name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users first issue'
        pr-message: 'Message that will be displayed on users first pull request'
        
    - name: First interaction
      uses: actions/first-interaction@v1.1.0
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Comment to post on an individual's first issue
        issue-message: 🎉 Thanks for opening your first issue here! Be sure to follow the issue template! ✔ Describe context of your commit then we will check its 👩‍💻
        # Comment to post on an individual's first pull request
        pr-message: 🎉 Thanks for opening this pull request! Please check out our contributing guidelines. ✔ We will notify an email for you as soon as possible 💌
